"""MITRE ATT&CK technique mapping and coverage.

Alerts arrive with the techniques their rule or product declares. The mapper adds techniques it can
infer from alert content (command lines, parent processes, mailbox rules, sign-in context) so product
alerts with coarse tags still land on the right sub-technique, and the coverage report says which
priority techniques have at least one enabled detection."""

from __future__ import annotations

import re
from functools import cache

import yaml

from aisoc import CONFIG
from aisoc.detections import Alert, rules

INFER = [  # (field, regex, technique)
    ("ProcessCommandLine", r"-enc(odedcommand)?\b", "T1059.001"),
    ("ProcessCommandLine", r"minidump|lsass", "T1003.001"),
    ("ProcessCommandLine", r"vssadmin.*delete\s+shadows", "T1490"),
    ("InitiatingProcessFileName", r"^(winword|excel|powerpnt|outlook)\.exe$", "T1204.002"),
    ("Destination", r"@", "T1114.003"),
    ("Description", r"encoded command", "T1059.001"),
    ("Description", r"lsass", "T1003.001"),
    ("Description", r"removed after delivery", "T1566.002"),
]
PRODUCT_NAME_MAP = {"Atypical travel": ["T1078.004"], "Password spray": ["T1110.003"]}


@cache
def catalogue() -> dict[str, dict]:
    return {t["id"]: t for t in yaml.safe_load((CONFIG / "attack-techniques.yaml").read_text())["techniques"]}


def name(tid: str) -> str:
    t = catalogue().get(tid)
    return t["name"] if t else tid


def tactic(tid: str) -> str:
    t = catalogue().get(tid) or catalogue().get(tid.split(".")[0])
    return t["tactic"] if t else "unknown"


def map_alert(a: Alert) -> list[str]:
    """Declared techniques plus inferred ones, de-duplicated, parent techniques dropped when a sub-technique is present."""
    found = list(a.techniques) + PRODUCT_NAME_MAP.get(a.name, [])
    for col, pattern, tid in INFER:
        val = a.fields.get(col)
        if isinstance(val, str) and re.search(pattern, val, re.I):
            found.append(tid)
    uniq = sorted(set(found))
    return [t for t in uniq if not any(o.startswith(t + ".") for o in uniq)]


def infer_text(text: str) -> list[str]:
    """Techniques suggested by a free-text command line (used by the investigator on raw rows)."""
    return sorted({tid for col, pattern, tid in INFER if col == "ProcessCommandLine" and re.search(pattern, text or "", re.I)})


def coverage() -> dict:
    """Priority techniques with at least one analytics rule or product mapping."""
    detected: dict[str, list[str]] = {}
    for r in rules():
        for t in r["techniques"]:
            detected.setdefault(t, []).append(r["id"])
    for alert_name, ts in PRODUCT_NAME_MAP.items():
        for t in ts:
            detected.setdefault(t, []).append(f"product:{alert_name}")
    priority = [t for t, v in catalogue().items() if v["priority"]]
    covered = [t for t in priority if t in detected]
    return {
        "priority": priority,
        "covered": covered,
        "missing": [t for t in priority if t not in detected],
        "ratio": round(len(covered) / len(priority), 3),
        "by_technique": detected,
    }


def navigator_layer(observed: dict[str, int] | None = None) -> dict:
    """An ATT&CK Navigator layer: score 1 = detection exists, comment lists the rules; observed counts optional."""
    cov = coverage()
    observed = observed or {}
    techs = []
    for tid in cov["priority"]:
        rules_ = cov["by_technique"].get(tid, [])
        techs.append(
            {
                "techniqueID": tid,
                "score": 1 if rules_ else 0,
                "comment": (", ".join(rules_) if rules_ else "no detection") + (f"; alerts in run: {observed[tid]}" if tid in observed else ""),
                "enabled": True,
            }
        )
    return {
        "name": "Halyard SOC detection coverage",
        "domain": "enterprise-attack",
        "versions": {"layer": "4.5", "navigator": "5.1"},
        "description": "Generated by aisoc attack --layer from detections/rules.yaml",
        "gradient": {"colors": ["#ff6666", "#66b366"], "minValue": 0, "maxValue": 1},
        "techniques": techs,
    }
